1. db.restaurante.find()
2. db.restaurante.find({}, {restaurant_id:1,borough:1,cuisine:1})
3. db.restaurante.find({}, {_id:0,restaurant_id:1,borough:1,cuisine:1})
4. db.restaurante.find({}, {_id:0,restaurant_id:1,name:1,borough:1,"address.zipcode":1})
5. db.restaurante.find({borough:"Bronx"})
6. db.restaurante.find({borough:"Bronx"}).limit(5)
7. db.restaurante.find({borough:"Bronx"}).skip(5).limit(5)
8. db.restaurante.find({"grades.score":{$gt:90}})
9. db.restaurante.find({$and:[{"grades.score":{$gt:80}},{"grades.score":{$lt:100}}]})
10. db.restaurante.find({"address.coord":{$lt:-95.754168}})
11. db.restaurante.find({$and:[{cuisine:{$ne:"American"}},{"grades.score":{$gt:70}},{"address.coord.1":{$lt:-65.754168}}]})
12. db.restaurante.find({cuisine: { $ne: "American" },grades: { $elemMatch: { score: { $gt: 70 } } },"address.coord.0": { $lt: -65.754168, $exists: true }})
13. db.restaurante.find({$and:[{cuisine:{$ne:"American"}},{"grades.grade":{$eq:"A"}},{borough:{$ne:"Brooklyn"}}]}).sort({cuisine:-1})
14. db.restaurante.find({name:{ $regex:/^Wil/}},{restaurant_id:1,name:1,borough:1,cuisine:1,_id:0})
15. db.restaurante.find({name:{ $regex:/ces$/}},{restaurant_id:1,name:1,borough:1,cuisine:1,_id:0})
16. db.restaurante.find({name:{ $regex:/Reg/}},{restaurant_id:1,name:1,borough:1,cuisine:1,_id:0})
17. db.restaurante.find({borough:"Bronx", $or:[{cuisine:"American"},{cuisine:"Chinese"}]})
18. db.restaurante.find({borough: {$in:["Staten Island", "Queens", "Bronx", "Brooklyn"]}},{restaurant_id:1,name:1,borough:1,cuisine:1,_id:0})
19. db.restaurante.find({borough: {$nin:["Staten Island", "Queens", "Bronx", "Brooklyn"]}},{restaurant_id:1,name:1,borough:1,cuisine:1,_id:0})
20. db.restaurante.find({"grades.score":{$lt:10}},{restaurant_id:1,name:1,borough:1,cuisine:1,_id:0})
21. db.restaurante.find({$and:[{cuisine:"Seafood"},{cuisine:{$nin:["American","Chinese"]}},{name:{$not:/^Wil/}}]},{restaurant_id:1,name:1,borough:1,cuisine:1,_id:0})
22. db.restaurante.find({grades:{$elemMatch:{grade:"A",score:11,date:ISODate("2014-08-11T00:00:00Z")}}},{restaurant_id:1,name:1,grades:1,_id:0})
23. db.restaurante.find({"grades.1.grade":"A","grades.1.score":9,"grades.1.date":ISODate("2014-08-11T00:00:00Z")},{restaurant_id:1,name:1,grades:1,_id:0})
24. db.restaurante.find({"address.coord.1":{$gte:42, $lte:52}},{restaurant_id:1,name:1,"address.street":1,"address.building":1,"address.coord":1,_id:0})
25. db.restaurante.find().sort({name:1})
26. db.restaurante.find().sort({name:-1})
27.db.restaurante.find().sort({cuisine:1},{borougt:-1})
28. db.restaurante.find({"address.street":{$ne:null}})
31. db.restaurante.find({name:{ $regex:/mon/}},{name:1,borough:1,"address.coord":1,cuisine:1,_id:0})
32. db.restaurante.find({name:{ $regex:/^Mad/}},{name:1,borough:1,"address.coord":1,cuisine:1,_id:0})


